[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "MobilityPlus"
versionNumber = "1.6.0"
description = "Adds advanced mobility equipment: Stilts MKII/MKIII, Speed Boots, Jump Pack, Rail Runner MKII, Speed/Jump Pads, and the Hover Pod personal vehicle!"
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-MobilityPlus"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/MobilityPlus.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
